#ifndef SIGNVERI_H
#define SIGNVERI_H


extern int result;

#include "basic.h"


void signverificationcyclic();//Generates Hash values by Hash_verify=(signature,1)*PK*transpose(signature,1) and compare with original hashvalue for authentication process

void print_signatureverification(int);//It prints hashvalues generated by verification process and result of authentication.





#endif
